config/routes.rb
WhyWeWork::Application.routes.draw do

  root "static_pages#home"
  match "/contact", to: "static_pages#contact", via: "get"
  match "/index", to: "companies#index", via:"get"

  resources :companies do
    resources :motives
  end

end

app/models/company.rb
class Company < ActiveRecord::Base

	has_many :motives, dependent: :destroy

	validates :name, presence: true

	def self.search(search)
		if search
			find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end
end

app/models/motives.rb
class Motives < ActiveRecord::Base
	belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	#create new company
	def new
		@company = Company.new
	end

	#create a company
	def create
		@company = Company.new(company_params)

		if @company.save
			redirect_to companies_path
		else
			render 'new'
		end
	end


	#delete
	def destroy
		@company = Company.find(params[:id])
		@company.destroy

		redirect_to companies_path
	end

	#list companys
	def  index
		@companies = Company.search(params[:search])
	end

	#edit
	def edit
		@company = Company.find(params[:id])
	end

	#update
	def update
		@company = Company.find(params[:id])

		if @company.update(company_params)
			redirect_to companies_path
		else
			render 'edit'
		end
	end

	def show
		@company = Company.find(params[:id])
	end

	private
		def company_params
			params.require(:company).permit(:name)
		end

end

app/controllers/companys_controller.rb
class CompanysController < ApplicationController
end

app/controllers/motives_controller.rb
class MotivesController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/helpers/motives_helper.rb
module MotivesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |x| %>
	<div class="bt10">
		<%= x.label :name, "Company Name" %><br>
		<%= x.text_field :name%>

		<%= x.submit "Add"%>
	</div>
	
<% end %>

app/views/companies/index.html.erb
<div id="contentmargin">

<div id="titles"> Current Listings</div>


<%= form_tag companies_path, :method => "get" do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>
	</p>
<% end %>

<% @companies.each do |company| %>
	<div class="listings">
		<%= link_to company.name, company_path(company), :class =>"list_item" %>
	</div>
<% end %>

<%= link_to "Add New Company", new_company_path, :class =>"tmargin20" %>

</div>

app/views/companies/new.html.erb
<div id="contentmargin">
<div id="titles"> Join The Movement </div>

<%= render 'form' %>


<%= link_to "Back to Listing", companies_path %>
</div>

app/views/companies/show.html.erb
<div id="contentmargin">
<div id="show">

<%= @company.name %>


</div>
</div>

app/views/layouts/_footer.html.erb
<span id="footer_links">
	<%= link_to "Contact", contact_path %>
	<%= link_to "Home", root_path %>
</span>

app/views/layouts/_header.html.erb
<header>
	<span id="header_logo">WhyWeWork   </span>

	<div id="listingbutton">
		<a href="/index" class="sunken">
			Explore Company Listings
		</a>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhyWeWork</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<div id="wrapper">
		<div id= "header">
			<%= render 'layouts/header' %>
		</div>
		<div id="content">
			<%= yield %>
		</div>
		<div id = "footer">
			<%= render 'layouts/footer' %>
		</div>
	</div>
</body>
</html>

app/views/static_pages/contact.html.erb
<div id="portrait">

<div class="leftside">
Tom
</div>
<div class="rightside">
Yang
</div>

</div>

app/views/static_pages/home.html.erb
<div id="artbackground">
<div id="portrait">
	<span class="missionstatement">
		Workplace Culture joins the Human Experience
	</span>
</div>
</div>